// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqChpm3KqGZ_of_xPGy7yJobesFbj-Gu0',
    appId: '1:866415355234:web:c3e5b9e967b2e7ca7d383b',
    messagingSenderId: '866415355234',
    projectId: 'first-app-66422',
    authDomain: 'first-app-66422.firebaseapp.com',
    databaseURL: 'https://first-app-66422-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-66422.firebasestorage.app',
    measurementId: 'G-SP9LEBMXJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFATvexO_a47sLQTgd4KYPk7P7JkfqwCA',
    appId: '1:866415355234:android:c8e88dbc1b8557087d383b',
    messagingSenderId: '866415355234',
    projectId: 'first-app-66422',
    databaseURL: 'https://first-app-66422-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-66422.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1iPAcOxBsGORZIRW1AckLTEoZxXrY2x8',
    appId: '1:866415355234:ios:3393e369fa1c3b6c7d383b',
    messagingSenderId: '866415355234',
    projectId: 'first-app-66422',
    databaseURL: 'https://first-app-66422-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-66422.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1iPAcOxBsGORZIRW1AckLTEoZxXrY2x8',
    appId: '1:866415355234:ios:3393e369fa1c3b6c7d383b',
    messagingSenderId: '866415355234',
    projectId: 'first-app-66422',
    databaseURL: 'https://first-app-66422-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-66422.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqChpm3KqGZ_of_xPGy7yJobesFbj-Gu0',
    appId: '1:866415355234:web:46b40fed90864f6a7d383b',
    messagingSenderId: '866415355234',
    projectId: 'first-app-66422',
    authDomain: 'first-app-66422.firebaseapp.com',
    databaseURL: 'https://first-app-66422-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-66422.firebasestorage.app',
    measurementId: 'G-BWNJC2TWS8',
  );
}
